# Basic Information 
title: Muhammad Zawish
position: Postdoctoral Researcher
affiliation: Technological University Dublin
affiliation_link: https://www.tudublin.ie/
#affiliation_logo: ./assets/img/illinois.svg
email: muhammad.zawish (at) tudublin.ie

# Search Engine Optimization (SEO)
keywords: muhammad zawish, zawish muhammad, muhammadzawish, zawishmuhammad, mzawish
canonical: https://www.linkedin.com/in/muhammadzawish/
description: Muhammad Zawish is a Postdoctoral researcher at the Technological University Dublin. His research lies in efficient, robust, and scalable machine learning.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?hl=en&user=otMUw_oAAAAJ&view_op=list_works&sortby=pubdate
github_link: https://github.com/mzawishq
linkedin: https://www.linkedin.com/in/muhammadzawish/
twitter: https://twitter.com/

# Images 
avatar: ./assets/img/img2.jpeg

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
